apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: amqpservers.infra.yaook.cloud
spec:
  group: infra.yaook.cloud
  names:
    kind: AMQPServer
    plural: amqpservers
    shortNames:
    - amqps
    - amqp
    singular: amqpserver
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current status of the Resource
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: The reason for the current status
      jsonPath: .status.conditions[?(@.type=="Converged")].reason
      name: Reason
      type: string
    - description: Informative messages
      jsonPath: .status.conditions[?(@.type=="Converged")].message
      name: Message
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              additionalFrontendCertDnsNames:
                items:
                  type: string
                type: array
              backendCAIssuerRef:
                description: ''
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              enabledPlugins:
                default: rabbitmq_management,rabbitmq_prometheus
                description: Plugins that should be enabled by AMQPServer
                type: string
              frontendIssuerRef:
                description: ''
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              imagePullSecrets:
                description: References to image pull secrets which should be included
                  in all Pods spawned directly or indirectly by this resource.
                items:
                  description: ''
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              imageRef:
                type: string
              implementation:
                default: RabbitMQ
                enum:
                - RabbitMQ
                type: string
              policies:
                additionalProperties:
                  additionalProperties:
                    properties:
                      applyto:
                        type: string
                      definition:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      pattern:
                        type: string
                      priority:
                        type: integer
                    required:
                    - pattern
                    - definition
                    - priority
                    - applyto
                    type: object
                  type: object
                type: object
              rabbitmqConfig:
                additionalProperties:
                  x-kubernetes-int-or-string: true
                type: object
              replicas:
                default: 3
                description: Number of replicas for the service
                type: integer
              resources:
                description: Resource limits for containers spawned by the AMQPServer
                properties:
                  rabbitmq:
                    description: Define resource requests/limits for the RabbitMQ
                      container
                    properties:
                      limits:
                        description: Define resource limits for the container
                        properties:
                          cpu:
                            description: CPU time limit for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory limit for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                      requests:
                        description: Define resource requests for the container
                        properties:
                          cpu:
                            description: CPU time request for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory request for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                    type: object
                type: object
              scheduleRuleWhenUnsatisfiable:
                default: ScheduleAnyway
                description: whenUnsatisfiable indicates how to deal with a Pod if
                  it doesn't satisfy the spread constraint
                enum:
                - ScheduleAnyway
                - DoNotSchedule
                type: string
              serviceMonitor:
                description: Configure the ServiceMonitor objects created by the operator.
                properties:
                  additionalLabels:
                    additionalProperties:
                      type: string
                    description: Additional labels to set on the ServiceMonitor metadata.
                    type: object
                type: object
              storageClassName:
                description: Storage class name. If unset, the cluster-wide default
                  storage class will be used. If that storage class is not set or
                  does not work, the deployment will be broken. Changing storage classes
                  after the initial rollout requires manual intervention.
                type: string
              storageSize:
                default: 8Gi
                description: Size to request for the PVC. Changing the size after
                  the initial rollout requires manual intervention.
                pattern: ^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$
                type: string
              tolerateNodeDown:
                default: false
                description: If set, Kubernetes will not evict the pod after 300s
                  in case of a NodeDown or Node unreachable.
                type: boolean
            required:
            - imageRef
            - storageSize
            - frontendIssuerRef
            - backendCAIssuerRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    lastUpdateTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      enum:
                      - Converged
                      - GarbageCollected
                      type: string
                  required:
                  - lastTransitionTime
                  - lastUpdateTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              observedGeneration:
                type: integer
              phase:
                enum:
                - Created
                - Updating
                - WaitingForDependency
                - Updated
                - BackingOff
                - InvalidConfiguration
                type: string
              replicas:
                type: integer
              updatedGeneration:
                type: integer
            required:
            - conditions
            - observedGeneration
            - phase
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
