apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: mysqlusers.infra.yaook.cloud
spec:
  group: infra.yaook.cloud
  names:
    kind: MySQLUser
    plural: mysqlusers
    shortNames: []
    singular: mysqluser
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current status of the Resource
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: The reason for the current status
      jsonPath: .status.conditions[?(@.type=="Converged")].reason
      name: Reason
      type: string
    - description: Informative messages
      jsonPath: .status.conditions[?(@.type=="Converged")].message
      name: Message
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              databasePrivileges:
                default:
                - ALL PRIVILEGES
                items:
                  pattern: '[A-Z ]+'
                  type: string
                type: array
              globalPrivileges:
                default: []
                items:
                  pattern: '[A-Z ]+'
                  type: string
                type: array
              passwordSecretKeyRef:
                description: ''
                properties:
                  key:
                    default: password
                    description: Key within the Secret to extract
                    type: string
                  name:
                    type: string
                required:
                - name
                type: object
              serviceRef:
                description: ''
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              user:
                type: string
            required:
            - user
            - serviceRef
            - passwordSecretKeyRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    lastUpdateTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      enum:
                      - Converged
                      - GarbageCollected
                      type: string
                  required:
                  - lastTransitionTime
                  - lastUpdateTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              observedGeneration:
                type: integer
              phase:
                enum:
                - Created
                - Updating
                - WaitingForDependency
                - Updated
                - BackingOff
                - InvalidConfiguration
                type: string
              updatedGeneration:
                type: integer
            required:
            - conditions
            - observedGeneration
            - phase
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
