---
- secret:
    name: SECRET_OSISM_KUBERNETES
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - Pq8lVvQiXGMFWwUfydoJ7P3DZe2DA3rkkS4WpMBEmOak1fV7nF7toagE3pHIpC4lOOK1D
          3waaYt6v1VZtykFoNBg3yGaYOeZ52+f4APiM7Tl+Qv4YADUEbdSEYtta/nDkzqPv9DUhd
          8jGDMwMB+/JHaMgcFQUVdtMFB33TVgqrRzYAedqwcoZa/zmkI5diYWqDrdbMprp/zcVjg
          LQk76QrqGg8iJzJDiQ8JnUaNeWIUkr48Dkiw3ONWLuoV1VlxsgQU4LjS8HnnI7N9/qwMQ
          DwYOAve6KiugiwG51k55rUUG2FL1fsr1zPEXCMIHKGZiT7kYOZT/dGg5rSMnZC+nqMeuV
          blAIleRIAOoUN9wwCpwzwK9Z+InrN2DFpWW9HjGfGtXTtDos/z2efcU/qr4sIs1fTREwI
          ulWR1g60FIaPVrVsHlzcJnqPbm7x/NpDJobcumxuC5z4Xcyfqr8bnrdvqDirZyr4LR6wG
          QaOJH/NhIQvp1t7S7zOio5fWi/nBdaTzjMk7bk6QbP/ZSbQybh2nzgEuncZuefNY9iaLR
          JHoPjXyz5Sy66DPETqKkiKGe54/OkGKLy5k+EXztq79OHo4ivdKW3ao1gJvA7dpY89+gp
          Z0ZMTt5JEsKVynFTABIsc69E+KwJaly2RnqajCUqTQmStksROSWXQXYaThgbBU=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - SCNF848hTkhOxmGS+XZ4YV5CHJD2GO/4qDCCJLabzsEfhRjMMFpp5k5YI9hM4gkcpq+pR
          L8Rt2Eqw3mNLr4AuG9VMDWdeKyBGXYCNVfZ9L71eZFfnoG5CvCtbq0GgR+8Oc94M6Af8+
          Lf1ao77josgzX6kv8tsOMlawCW7Q47IxemWZn5SNFFOzw5EHSs9VVwV52f/ZHdzqJmnfk
          BG4nsHwlKhrQX3iLtlJxtnn0HJWywsYfeH3ZefKcrm1MZZf8o7mwB7HRad1vGZJAw6xKd
          qFf7nyZqe3RcBMZf4zIvoIobRneToWTsInhFxEijlfogoAST6MOCpFobYm0lFXdUY148z
          44y2DVLRuNN6Gqnr5j8IST7RPgTLwnGI76yFAwIO8tjRG9CBjmUz9wuN4qcpbQkoPXuT6
          DwYuV79pW4y8Z6WqBJ6C7xG+Knx/OQQ+sjDbwQoZHVeRaPJ2IzegsdYGu5kwZVOeXQ/Nk
          a83E9oAcXHe0LDed5jGfQ0yBiti45z3xTF9MpcLHSY2Y7NjqrcM2QLggxdgaDE63BC6GD
          w2Yc/sg3T8OjR4ZJnkWLRDUPZ+UQMtykqzE7d0DGTBYUFrvnKd3ZB5yi96roZoKVuYAfY
          +bcCDx5jX+G7+jPsLZpZh5DGvJ7zc235pT8AoYApk1E8YTFVaZPrYDWe2VAxkw=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - mfdwWUdhoPMNJX1z3ioAGEscQxn/T7nKjPieDi3JEcAUop7gtLxaL19Sw//tzLqmbdTad
          2JV77mlpf2jT59mnebl0YeMTKhVMKJ0tm92kZ2o8j7a8PO1NSEjkkrSkkLnRulsYSnx+W
          Vtvacr7Q2z+Z2Qtyj7C0vW5YnkDDQ6mZ4r6VjK4qerxVF0dnxiV0/MJd2JFyOuEPvA9j7
          zgi92Q4Y4k2eog4zNqDUDrmN9vfF8mIMua5W5BdWuCPqPxk2v4dO7QXnFE+ER2DqzCwf+
          6vHLGLyoRFiVje667B6qQEvgdc6pw+3a1znvospZyvjwc4ZG7v18rpvgAdmgF2omcofPz
          EyIfsxUniVsNFabeE8U6cU+kUjPlkRm8dzKSN6YvrHaZu3b/jacTIG/khEWyoDhFfkbAs
          q2HPLBhew0TeLl+KqOaQEa07T6x7mpxp5CuQ2ESOt6/qk9pIb5Sgi4OBL4oM26WpUHgYW
          iU0piew7eSwWXSvXwf0TVgnMRv/4ityumZe5gEzKzYY8UBgDPWVTj7uabL1Lli2C7R95Z
          RZCELIzP9fE6xCPPyjKTN7KVwTq+d/8P6Nth0AYkD6ahPAXUSuTeXMeZYB/AtUReLYHJY
          k7S4YQWsygbt/gmUXTCfHB4u+BbdGez5rNeh15fBYPmfwT8SWVSKjHKzuLCenc=

- semaphore:
    name: semaphore-osism-kubernetes-push
    max: 1

- job:
    name: osism-kubernetes-build
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-osism-kubernetes-push
    abstract: true
    semaphores:
      - name: semaphore-osism-kubernetes-push
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true
      push_sbom: true

- job:
    name: osism-kubernetes-push
    parent: abstract-osism-kubernetes-push
    secrets:
      - name: secret
        secret: SECRET_OSISM_KUBERNETES
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - hadolint
        - osism-kubernetes-build
        - python-black
        - yamllint
    gate:
      jobs:
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - hadolint
        - osism-kubernetes-build
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - osism-kubernetes-push
    post:
      jobs:
        - osism-kubernetes-push:
            branches: main
    tag:
      jobs:
        - osism-kubernetes-push
