---
- secret:
    name: SECRET_OSISM_KUBERNETES
    data:
      DTRACK_API_KEY: !encrypted/pkcs1-oaep
        - yYLR67nKZWZWPcwWY/iAjktV6s378nL8VWeTe6fhIR4mBu3/to9nG4sHrPxuM+RnMy1YX
          zRIQd5cTSl2uOsgf3QpzLTgcdBe6/sUNCbo4O6/+El61yj3iV8DyY0+yjxsWHfx2EQveD
          FxTEf/oZGlDO5RuHl3kU6BBiO0LWVQD86aNboVrvI/lcsx0CDHWt0yQszFDM3XjUjs/RS
          NM86RCpYRUYMwkalySSO+yI7W+6JjrJSJGQm/KOmSFuFMdXxHkVNaWucUfkllKhwDmKne
          nCqRPc8plvNekbsJublZN84b3C0A2SnEXg8StZBMcjBE5/1S0I4iL3eJuoYyN9zYLT3yi
          QgU7tCKqp+e7cRKNCzMftWL1vmhrxYCt2qifmYYKVETTOCl6RQYb5nKyCO3u6lBKsbI5y
          zBBin7pybRTwDe/yRfrIHChkELrFqLX5IuZT117cteR2s9+Fi9qXEA3ocrGA/mtqMBDtx
          7GW0IAcbSPJeO3TxpC7dOnTUhjfCilDc2qrvG1SkIqRoG/yJVt6rZEbo3z77w4LfZIDRI
          Wzc5PrJbnc20DY7/a8mXEJ8LZg5VRVunZx3eFi+re84gK7cGtilBRsCiVc+syNW1FjHDz
          NgHE/kZUi5enGt8V29/FjHadzYhMNjAbToXcAqxK+t959kAk3oYnYXYEWaQN1M=
      DOCKER_PASSWORD: !encrypted/pkcs1-oaep
        - bJ85AijN4dA1sCQSeYRdcraUfsLByH/fobv2Q2KzURIp+2SIUvtnzytUK/GfC07ZJjqY6
          5Gw0nMKwnyZh+xWXPzmfyez8zXriDcHp9A6RYnrtmP5UVhRsfmItBWoL0pGxJOwBZGq0f
          aNaHMjcGwOV1lgjRIz5zH7yDsG636f3md9BggCB+NTjAaI4Xi+SxAhIFVJ41kbSjgD7Yo
          LMQkTs8WVFSe6z4cfr7JS6NzFqrdPcobgeCI9WHB7xF9AkBMWCw3sNRziNiqKUw/nLgOI
          PYO8tpE0W7riFmTd9u4UU1wBa0lt4bZSbVmwO9rO5AvJPKMJjiPoHAiIAXV9fVagPcqj5
          Aa68D8T1gx+c+sy30KWV+txgkZrDlEuGNqlg2EHuQ5wAvjCR1AWPiS+RnK/Cm7sEhL1yD
          IE/nGctrw0rcK+FyieDiAZYcnjKD2Ad3OIBlSGA7ImMaSnU80tPBzRaIulYSVKaca2a07
          l75gqWGAWHym89ahkuYjkOd145Ba6GHsk2gebSOrtSIw8+/4RQG1ztxmFkGe80tcuCQvK
          iZb46k9jLqqGsmXEoHGBXy7LG4tuvpiNw0u4ylkChjfLXQXwotSPVs+nBxmxWIh6on5tH
          Xt4VI34Q3X2Q5BMJUJOOIrDyr0J3PYkJmv8JLGj1S2DCe+TJ6Zh0OqIzn57k+E=
      DOCKER_USERNAME: !encrypted/pkcs1-oaep
        - n4jElls3pVy/hqq05AUr49TrrF6RcD810viW5hlj9ls9QOtkvGOgFCwQESH/RJ9kLtsU5
          gT5FvLiBJQ5LwfYD7mzoO1n0ce2cOHcjRVMs/FO3A/ZBciozUPJYk9HRUkbhfvVEvyqKu
          jzWkh6ZTiR3qUd0bzTvli7NDqVhrI2OS6KNfTVH5DQs0rpIId4HIuY9NS9yNAhOqGxOFP
          ca5/APpB0ToJ/g13yLS5vZiRr0OZrUiqvkwJauWLeaOCj4UrTM1XBrGwyoj57VA6/WY0E
          oZjCfLwWKbci7lUKX1gxSvH1VFLEHc6etkMvNFJTnMwZxYY5jGVTsiyQTd2OufWrXrzGQ
          0Yx1mlqFPKtRYUIJU1bJX7b/y6n5L/p6DVW5TYsuaQIZYbzNC9vMzOYhYkTFAiKRlJ178
          5cEk5OgyMzFN/cENEeBViMT7cyfB6RijwmaVyjP3K8lQbROas5qgURSzkIbBdgjZ9Ohgw
          0hgZkIkFHOSTmQfP0ILImp6KJOABJL5bSPUgJMO5x4/qutIznXDQpr6GKI89Z2JROPDY3
          USDwgvhyRXrwx0MLkYW8ZCKx6qb8kt7rDao8iRXUaZ5XzZx3mnLfTCX2iHRnKHgYZKYCA
          tRdw4576541WHVbdLJH/lmMJqrmw5I+vgA1wzochVHUNJKi9CwWSTxSc+n2rjk=
      COSIGN_PASSWORD: !encrypted/pkcs1-oaep
        - skMi/a0QQQ4qoulrWOGSmmn3AzkMmCmNetaRvgVZ9UvCOy/MSSWmg147jwPFsz1R9E4AR
          F8HhCQoEfGvxxD8ver4pFtNv8UPLzzuiM52/9FhEGrwC7FfjNIgqt9fDLwlxZNkAjeSA0
          pB2Mrr0bM+K72yWgUc8z96kZD9mpGj+WVaUgJXlot1rOBBgASs2smYYw5gRZsIWYUm+jQ
          3Ua4VisdKYC1me5oN5brKBZ5N+rXlc0M9KMW7DJopE0pcOMX6XTXkbLl0r93muRVOeT30
          Qa/85TxzC8AFHKt6qfm11/j7eIKy8ZcAU16J0etJbnY2gt7zPZFwblUB0V9WYFD0dhe4R
          L/RWcLNdeW9rhkAaoWC4Y9Wz9I5QhxB6H4IjEiJ86KHD5AlHzAOHfOyPQq+sWgJEAiK7M
          ceiWGlOCZvrD+mSZBLH4iyuaiGpbrkFbgoD0fOPnlPZ9ew2KRlLdKy3RaiVxGFEvYspoD
          k0FjIKH/pMe7cJvipV0Advh8K7wcNqShYfRIkImR0NgXK+D9ThAQsX9a/kzPuhxT1QdLU
          qz130+XNhVcv2oF0zK1QvdzgsYwEG0kM3bbuqdVkvv5To+vd9hJjGikbS0zj0VrtZit7b
          1KIlCl2MKqYpcHl72nmMearBAAd7v3YeXkW+tgBqpAus26AoJ3Ely9SMdgyXXM=
      COSIGN_PRIVATE_KEY: !encrypted/pkcs1-oaep
        - FhqCgrAIZBKMUKrBk67fj4sKHbnV+9yTzQosus+xUtqOq5Z7JF2K/O9IDgp2mCCA3Yoks
          WDrVPdqRmhaLm3ZefhFWwQODiLkrB0AF2VIOQumWrClYs71E1CC2oKyG9C/fHWvcSrx/q
          FjPawEmXT4MW+sQ3krABEY6YUvwa9mzFaAiJwNSx4O7lH5P13YT4Vm425tgJKcUOGGc2N
          gY75KzxNgEpI8pJNJD8Hs8X7bM4duqoEgx8HQagdV1QJd6TWlyR5ZcRXVsa8k5f+K2Ejt
          FU2s2omFKwYwLQlVYNDZz2CsHQt3gemlgyKTmQtbEm67Tw3jv49E11RMAXlqR8JyVeiVm
          uSHQN9UXumSmfiNEyzp/aDe5rsg/4SdXnvcl4UFB74z5lfDFZLrtKxgecZ0gyTdnfYtXH
          1TNbb2zchYAs1RlCsHvUuWTt8PvZj/kbTe+hFsw/PF6FfJ0IUAAJwYAnjvfglpn5l+miv
          OSuqn9RM8AhLbRJ/cKVvKHpMde3OLD/vCYUIKn7wX6mnDDT0h73srYmGiHL/dyt0kDpfZ
          WDXhMwWopueJV7TkdTyvvpE66Vpc1S1SRsAXUrWJADRxAIWeptSwkGdqc8i45ChVEEq4y
          nNjqgoi9nfgTadT51aGmQIImBFM2+73mO0AazB8j6N+rWu2GAVCNjDaDGm8Vko=
        - yvNOY61vYWFp++VsRhxzCjDdrunH9Whf3HuMYPdIISKr071rwCVNOkQjqwIrcFbjH7tha
          Y4SD6Ed0N4BIc20LdSs47Fwuxg2t878rmlNzZpksIYMxf9vqILRoBdmBstDn9NhOHCHA4
          dFWlOXeUvQw4fjHinHJ+zvB/kQgkmMVBzpF1HCggbHT25bSkzkzLyM2Gc7+mIWo8T7ZIm
          ZUhF53BruTkLThSG6WXZlRik77D3gWrMJVkmTmwfWHvtXo9p9bQ6uOrNNg356YRHQyq1u
          yfvL/hJkn6CMiMcxVODkrUnKNCspyHw6e22/MhG6akqwi1fHHNdeazZhegZUKePeQnbsu
          75erMLcU/b0C0gLJgVl5fi0/hSZqQcSPp/GRaxFR86zmngXvrqjxfYVCc8Gn0tmkhZC2g
          CsVWrZSZ0AowhEzI4DV9Yhk5IwxqX2EuLF8wDHVuWO6+0VGy2Qjd178RuHWABMjpR6Ksq
          oL7NxMxWDOQhpPTioiPbLdLvD90qleqrHwvrfIo64Emh5wqWulx588saCpkZacKq2XHng
          /x2QffZfqs1Gfxwi82m8XreeGc2GTEkeJ0XgYGOFzT6nBoBRM3zkD354s9/mloovp9Rb9
          p18bk+Olw6NU2VlADZrxanvXnjHrqVqAnnewfOBEWfyxho64mA8G8GWy6o0Euk=

- semaphore:
    name: semaphore-osism-kubernetes-push
    max: 1

- job:
    name: osism-kubernetes-build
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital

- job:
    name: abstract-osism-kubernetes-push
    abstract: true
    semaphores:
      - name: semaphore-osism-kubernetes-push
    pre-run: zuul-playbooks/pre.yml
    run: zuul-playbooks/build.yml
    vars:
      docker_namespace: osism
      docker_registry: osism.harbor.regio.digital
      push_image: true
      push_sbom: true

- job:
    name: osism-kubernetes-push
    parent: abstract-osism-kubernetes-push
    secrets:
      - name: secret
        secret: SECRET_OSISM_KUBERNETES
        pass-to-parent: true

- project:
    merge-mode: squash-merge
    default-branch: main
    check:
      jobs:
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - hadolint
        - osism-kubernetes-build
        - python-black
        - yamllint
    gate:
      jobs:
        - ansible-collection-ensure-readme
        - ansible-lint
        - flake8
        - hadolint
        - osism-kubernetes-build
        - python-black
        - yamllint
    periodic-daily:
      jobs:
        - ansible-lint
        - flake8
        - hadolint
        - python-black
        - yamllint
    periodic-midnight:
      jobs:
        - osism-kubernetes-push
    post:
      jobs:
        - osism-kubernetes-push:
            branches: main
    tag:
      jobs:
        - osism-kubernetes-push
