apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: yaookdisruptionbudgets.yaook.cloud
spec:
  group: yaook.cloud
  names:
    kind: YaookDisruptionBudget
    plural: yaookdisruptionbudgets
    shortNames:
    - ydb
    - ydbs
    singular: yaookdisruptionbudget
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              disruptiveMaintenance:
                default: false
                description: If this flag is true, virtual machines will be cold migrated
                  from the hypervisor
                type: boolean
              maxUnavailable:
                minimum: 0
                pattern: ^(100|[0-9]{1,2})%$
                x-kubernetes-int-or-string: true
              nodeSelectors:
                items:
                  properties:
                    matchLabels:
                      additionalProperties:
                        type: string
                      type: object
                  required:
                  - matchLabels
                  type: object
                type: array
              preventDeletion:
                default: false
                description: If this is true, Resources will not be deleted immediately
                  if their coresponding node-label is removed. Manual deletion of
                  novacomputenode resource is needed.
                type: boolean
              spareNodes:
                properties:
                  amount:
                    minimum: 1
                    pattern: ^(100|[0-9]{1,2})%$
                    x-kubernetes-int-or-string: true
                  spareAggregateRef:
                    description: ''
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  spotTrait:
                    type: string
                required:
                - amount
                - spareAggregateRef
                type: object
            required:
            - nodeSelectors
            - maxUnavailable
            type: object
          status:
            properties:
              nodes:
                items:
                  properties:
                    availableInstances:
                      type: integer
                    configuredInstances:
                      type: integer
                    existingInstances:
                      type: integer
                    lastUpdateTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    readyInstances:
                      type: integer
                    spareNodes:
                      items:
                        type: string
                      type: array
                    type:
                      type: string
                    updatedInstances:
                      type: integer
                  required:
                  - configuredInstances
                  - existingInstances
                  - updatedInstances
                  - readyInstances
                  - availableInstances
                  - lastUpdateTime
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
