apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: horizondeployments.yaook.cloud
spec:
  group: yaook.cloud
  names:
    kind: HorizonDeployment
    plural: horizondeployments
    shortNames:
    - horizond
    - horizonds
    singular: horizondeployment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current status of the Resource
      jsonPath: .status.phase
      name: Phase
      type: string
    - description: The reason for the current status
      jsonPath: .status.conditions[?(@.type=="Converged")].reason
      name: Reason
      type: string
    - description: Informative messages
      jsonPath: .status.conditions[?(@.type=="Converged")].message
      name: Message
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              caCertificates:
                description: CA Certificates that should be added to all services
                  can be placed here. CAs that issue certificates to the service are
                  automatically added and do not need to be specified.
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              imagePullSecrets:
                description: References to image pull secrets which should be included
                  in all Pods spawned directly or indirectly by this resource.
                items:
                  description: ''
                  properties:
                    name:
                      type: string
                  required:
                  - name
                  type: object
                type: array
              ingress:
                description: Ingress configuration
                properties:
                  createIngress:
                    description: Create the k8s ingress object. The default value
                      is true
                    type: boolean
                  externalCertificateSecretRef:
                    description: Reference to a Kubernetes TLS Secret containing the
                      TLS certificate and keys to use for this endpoint. If unset,
                      a certificate will be generated using the Issuer configured
                      via issuerRef at the top level.
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  fqdn:
                    description: The outer fully-qualified domain name of the Ingress
                    type: string
                  ingressClassName:
                    default: nginx
                    description: Class of the Ingress to use
                    type: string
                  port:
                    description: Port number under which the Ingress is available.
                      This is required to be set to generate the full URL e.g. for
                      KeystoneEndpoints
                    type: integer
                required:
                - fqdn
                - port
                type: object
              issuerRef:
                description: Reference an issuer for the certificates used internally
                  by YAOOK (and, by default, also for external services unless overridden).
                properties:
                  name:
                    default: ca-issuer
                    description: Name of the cert-manager Issuer object
                    type: string
                type: object
              keystoneRef:
                description: Keystone deployment to link this service to
                properties:
                  kind:
                    default: KeystoneDeployment
                    description: Specify the kind of Keystone deployment to reference
                    enum:
                    - KeystoneDeployment
                    - ExternalKeystoneDeployment
                    type: string
                  name:
                    type: string
                required:
                - name
                type: object
              replicas:
                default: 3
                type: integer
              resources:
                properties:
                  horizon:
                    description: Define resource requests/limits for the  container
                    properties:
                      limits:
                        description: Define resource limits for the container
                        properties:
                          cpu:
                            description: CPU time limit for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory limit for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                      requests:
                        description: Define resource requests for the container
                        properties:
                          cpu:
                            description: CPU time request for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory request for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                    type: object
                  service-reload-external:
                    description: Define resource requests/limits for the  container
                    properties:
                      limits:
                        description: Define resource limits for the container
                        properties:
                          cpu:
                            description: CPU time limit for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory limit for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                      requests:
                        description: Define resource requests for the container
                        properties:
                          cpu:
                            description: CPU time request for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory request for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                    type: object
                  ssl-terminator-external:
                    description: Define resource requests/limits for the  container
                    properties:
                      limits:
                        description: Define resource limits for the container
                        properties:
                          cpu:
                            description: CPU time limit for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory limit for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                      requests:
                        description: Define resource requests for the container
                        properties:
                          cpu:
                            description: CPU time request for the container
                            pattern: ^[1-9][0-9]*m?$
                            type: string
                          memory:
                            description: Memory request for the container
                            pattern: ^[1-9][0-9]*(E|P|T|G|M|k|Ei|Pi|Ti|Gi|Mi|Ki)?$
                            type: string
                        type: object
                    type: object
                type: object
              scheduleRuleWhenUnsatisfiable:
                default: ScheduleAnyway
                description: whenUnsatisfiable indicates how to deal with a Pod if
                  it doesn't satisfy the spread constraint
                enum:
                - ScheduleAnyway
                - DoNotSchedule
                type: string
              serviceMonitor:
                description: Configure the ServiceMonitor objects created by the operator.
                properties:
                  additionalLabels:
                    additionalProperties:
                      type: string
                    description: Additional labels to set on the ServiceMonitor metadata.
                    type: object
                type: object
              targetRelease:
                description: The release to deploy. Changing this will trigger an
                  upgrade.
                enum:
                - zed
                - '2023.1'
                - '2023.2'
                - '2024.1'
                - '2024.2'
                type: string
            required:
            - keystoneRef
            - ingress
            - targetRelease
            - issuerRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    lastUpdateTime:
                      pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      enum:
                      - Converged
                      - GarbageCollected
                      type: string
                  required:
                  - lastTransitionTime
                  - lastUpdateTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              installedRelease:
                description: The last successfully deployed release.
                type: string
              nextRelease:
                description: The next release to roll out. This differs from installedRelease
                  during upgrades and from targetRelease during multi-step upgrades.
                type: string
              observedGeneration:
                type: integer
              phase:
                enum:
                - Created
                - Updating
                - WaitingForDependency
                - Updated
                - BackingOff
                - InvalidConfiguration
                type: string
              updatedGeneration:
                type: integer
            required:
            - conditions
            - observedGeneration
            - phase
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
