---
- name: Deploy mariadb-operator crds
  kubernetes.core.helm:
    release_name: "{{ crds_mariadb_operator_helm_release_name }}"
    chart_ref: "{{ crds_mariadb_operator_helm_chart_ref }}"
    release_namespace: "{{ crds_mariadb_operator_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _crds_mariadb_operator_helm_values | combine(crds_mariadb_operator_helm_values, recursive=True) }}"
  when: crds_mariadb_operator | bool

- name: Deploy prometheus operator crds
  kubernetes.core.helm:
    release_name: "{{ crds_prometheus_operator_helm_release_name }}"
    chart_ref: "{{ crds_prometheus_operator_helm_chart_ref }}"
    release_namespace: "{{ crds_prometheus_operator_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _crds_prometheus_operator_helm_values | combine(crds_prometheus_operator_helm_values, recursive=True) }}"
  when: crds_prometheus_operator | bool

- name: Deploy yaook operators crds
  kubernetes.core.helm:
    release_name: "{{ crds_yaook_operators_helm_release_name }}"
    chart_ref: "{{ crds_yaook_operators_helm_chart_ref }}"
    release_namespace: "{{ crds_yaook_operators_helm_release_namespace }}"
    create_namespace: true
    kubeconfig: /share/kubeconfig
    wait: true
    values: "{{ _crds_yaook_operators_helm_values | combine(crds_yaook_operators_helm_values, recursive=True) }}"
  when: crds_yaook_operators | bool
