apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-nfs-nodeplugin-cr
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
