apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ceph-csi-operator.fullname" . }}-operatorconfig-editor-role
  labels:
  {{- include "ceph-csi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - csi.ceph.io
  resources:
  - operatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ceph.io
  resources:
  - operatorconfigs/status
  verbs:
  - get
