---
- name: Check for PXE-booted system
  block:  # noqa: osism-fqcn
    - name: Check if system is PXE-booted
      ansible.builtin.command:
        cmd: cat /proc/cmdline
      register: boot_cmdline
      changed_when: false
      check_mode: false

    - name: Set fact for PXE-booted system
      ansible.builtin.set_fact:
        is_pxe_booted: "{{ 'root=/dev/nfs' in boot_cmdline.stdout }}"
      when: boot_cmdline.stdout is defined

    - name: Include http_proxy configuration tasks
      ansible.builtin.include_tasks: http_proxy.yml

- name: Deploy K3s http_proxy conf
  ansible.builtin.include_tasks: http_proxy.yml
  when: proxy_env is defined

- name: Create /etc/rancher/k3s directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: k3s_resolvconf_nameserver | length > 0

- name: Create custom resolv.conf for k3s
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/rancher/k3s/resolv.conf
    owner: root
    group: root
    mode: "0644"
  when: k3s_resolvconf_nameserver | length > 0

- name: Configure the k3s service
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: "0755"

- name: Manage k3s service
  ansible.builtin.systemd:
    name: k3s-node
    daemon_reload: true
    state: restarted
    enabled: true
