{{- define "yaook.operator-lib.Service" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yaook.operator-lib.fullname" . }}
  labels:
    {{- include "yaook.operator-lib.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "yaook.operator-lib.selectorLabels" . | nindent 6 }}
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
{{- end }}
