---
collections:
  - name: ansible.utils
    source: https://galaxy.ansible.com
    version: '6.0.0'
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: '2.1.0'
  - name: community.general
    source: https://galaxy.ansible.com
    version: '11.2.1'
  - name: kubernetes.core
    source: https://galaxy.ansible.com
    version: '6.0.0'
  - name: osism.commons
    source: https://galaxy.ansible.com
    version: '0.20250824.0'
