{{- if .Values.pluginsManager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headlamp.fullname" . }}-plugin-config
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
data:
  plugin.yml: |
    {{ .Values.pluginsManager.configContent | nindent 4 }}
{{- end }}
