{{- define "yaook.operator-lib.RoleBinding" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "yaook.operator-lib.fullname" . }}
  labels:
    {{- include "yaook.operator-lib.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yaook.operator-lib.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "yaook.operator-lib.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
