---
- name: Apply change-labels tasks from role rook
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local
  gather_facts: false

  tasks:
    - name: Include change-labels tasks from role rook
      ansible.builtin.include_role:
        name: rook
        tasks_from: change-labels.yml
