---
- name: Manage labels, annotations, and taints on all k3s nodes
  hosts: "{{ hosts_k3s_all|default('k3s_all') }}"
  gather_facts: false

  vars:
    k3s_add_labels_groups: []
    k3s_add_annotations_groups: []
    k3s_add_taints_groups: []

  tasks:
    - name: Merge labels, annotations, and taints
      ansible.builtin.set_fact:
        _k3s_add_labels: "{{ lookup('community.general.merge_variables', '^k3s_add_labels__.+$', initial_value=k3s_add_labels | default([], true), groups=k3s_add_labels_groups) }}"
        _k3s_add_annotations: "{{ lookup('community.general.merge_variables', '^k3s_add_annotations__.+$', initial_value=k3s_add_annotations | default([], true), groups=k3s_add_annotations_groups) }}"
        _k3s_add_taints: "{{ lookup('community.general.merge_variables', '^k3s_add_taints__.+$', initial_value=k3s_add_taints | default([], true), groups=k3s_add_taints_groups) }}"
        cacheable: false

    - name: Manage labels
      ansible.builtin.shell: |
        set -o pipefail

        export KUBECONFIG=/share/kubeconfig
        kubectl label node {{ inventory_hostname.split('.')[0] }} {{ item }} --overwrite
      args:
        executable: /bin/bash
      changed_when: false
      loop: "{{ _k3s_add_labels }}"
      delegate_to: localhost

    - name: Manage annotations
      ansible.builtin.shell: |
        set -o pipefail

        export KUBECONFIG=/share/kubeconfig
        kubectl annotate node {{ inventory_hostname.split('.')[0] }} {{ item }} --overwrite
      args:
        executable: /bin/bash
      changed_when: false
      loop: "{{ _k3s_add_annotations }}"
      delegate_to: localhost

    - name: Manage taints
      ansible.builtin.shell: |
        set -o pipefail

        export KUBECONFIG=/share/kubeconfig
        kubectl taint node {{ inventory_hostname.split('.')[0] }} {{ item }} --overwrite
      args:
        executable: /bin/bash
      changed_when: false
      loop: "{{ _k3s_add_taints }}"
      delegate_to: localhost
