---
- name: Apply label-nodes tasks from role rook
  hosts:
    - "{{ hosts_manager|default(groups['manager'][0])|default('localhost') }}"
  connection: local
  gather_facts: false

  tasks:
    - name: Include label_nodes tasks from role rook
      ansible.builtin.include_role:
        name: rook
        tasks_from: label-nodes.yml
